repos:
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.8.4
    hooks:
      - id: snakefmt
  - repo: local
    hooks:
      - id: conda-lock
        name: conda-lock
        files: environment.yml
        entry: conda-lock lock --check-input-hash -p linux-64 -p osx-64 --mamba -f
        language: python
        additional_dependencies: ["conda-lock==1.4.0"]
        verbose: true