name: tors-instance-generator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - pip:
    - wonderwords
  - snakemake
  - ruff
  - protobuf
  - snakedeploy
  - graphviz
  - networkx
  - ipykernel
  - matplotlib
  - scipy