name: tors-instance-generator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - git
  - cxx-compiler
  - pip:
    - wonderwords
    - git+https://github.com/ReubenJ/snakemake.git@fix/long-slurm-account-names
  - ruff
  - protobuf
  - snakedeploy
  - graphviz
  - networkx
  - ipykernel
  - matplotlib
  - scipy
  - virtualenv